# Generated by Django 5.0.6 on 2024-07-09 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('uid', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateField(auto_now_add=True)),
                ('modified', models.DateField(auto_now=True)),
                ('roomName', models.CharField(default='none', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
