# Generated by Django 5.0.6 on 2024-07-10 11:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learnDjango', '0003_nepalidate_rename_amount_rentpayment_paid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='floor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='room',
            name='rent',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10000.0)]),
        ),
    ]
