# Generated by Django 5.0.6 on 2024-07-11 12:41

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learnDjango', '0007_nepalidate_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='NepaliMonth',
            fields=[
                ('uid', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateField(auto_now_add=True)),
                ('modified', models.DateField(auto_now=True)),
                ('month', models.CharField(default=' Unknown', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NepaliYear',
            fields=[
                ('uid', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateField(auto_now_add=True)),
                ('modified', models.DateField(auto_now=True)),
                ('year', models.DecimalField(decimal_places=0, default=2080, max_digits=4, validators=[django.core.validators.MinValueValidator(2080), django.core.validators.MaxValueValidator(3000)])),
                ('current', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='rentpayment',
            name='dateId',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='learnDjango.nepalimonth'),
        ),
        migrations.DeleteModel(
            name='NepaliDate',
        ),
    ]
