# Generated by Django 5.0.6 on 2024-07-11 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learnDjango', '0008_nepalimonth_nepaliyear_alter_rentpayment_dateid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nepaliyear',
            name='current',
            field=models.BooleanField(default=True),
        ),
    ]
