# Generated by Django 5.0.6 on 2024-07-10 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learnDjango', '0005_alter_renthistory_totalremaining_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='floor',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=1),
        ),
    ]
