# Generated by Django 5.0.6 on 2024-07-11 12:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learnDjango', '0006_alter_room_floor'),
    ]

    operations = [
        migrations.AddField(
            model_name='nepalidate',
            name='year',
            field=models.DecimalField(decimal_places=0, default=2080, max_digits=4, validators=[django.core.validators.MinValueValidator(2080), django.core.validators.MaxValueValidator(3000)]),
        ),
    ]
